- src/bdchm/schema/bdchm.yaml
Add permissible values under the VisitCategoryEnum
> Add visit category enums

- src/bdchm/schema/bdchm.yaml
this is same as the visit type class in OMOP concept table
> Added 80 visitProvenanceEnum permissible values

- src/bdchm/schema/bdchm.yaml
Updated the range of visit_category from string to VisitCategoryEnum and the range of visit_provenance from string to VisitProvenanceEnum in order to constrain these fields to those defined ranges.
> update range for VisitCategoryEnum and VisitProvenanceEnum

- src/bdchm/schema/bdchm.yaml
Added a new entity named Consent to capture consent code, valid from and valid to attributes.
> added new consent entity and attributes to participant and research study

- CONTRIBUTING.md
- mkdocs.yml
Find and replace references in source code to `https://github.com/bfurner/bdchm` with the following new location 
`https://github.com/RTIInternational/NHLBI-BDC-DMC-HM`
> update references to old repo with new repo location

- mkdocs.yml
- src/bdchm/schema/bdchm.yaml
Made updates to include the new documentation URL
> update references to documentation from bfurner to rtiinternational

- src/bdchm/schema/bdchm.yaml
This PR covers the addition of Observation and ObservationSet entities and cleanup of some existing entities in the model
> Observation entities

- src/bdchm/schema/bdchm.yaml
- src/docs/about.md
This is still in progress. Need to make decisions about where to get various enum values.
> 17 drug exposure and device exposure

- src/bdchm/schema/bdchm.yaml
bugfix for tab character that caused failure of docs build
> bugfix for tab character that caused failure of docs build

- src/bdchm/schema/bdchm.yaml
Changes to Observation to capture age at observation and associated visit.  This is related to [issue 37](https://github.com/RTIInternational/NHLBI-BDC-DMC-HM/issues/37)
> Changes to Observation to capture age at observation and associated visit

- resources/human-readable-harmonized-variable-documentation/harmonization_documentation_generator.py
- resources/human-readable-harmonized-variable-documentation/topmed-variable-documentation.md
To help understand inputs to R functions.
Would be nice to have meaningful variable names instead of just phs/pht/phv identifiers. Not sure it's worth the effort to get them though.
> Added list of component variables to bottom of doc

- src/bdchm/schema/bdchm.yaml
Removed unnecessary attributes of ObservationValue (type, name) and added associated_visit to ObservationSet
> Updates to ObservationValue and Observation

- src/bdchm/schema/bdchm.yaml
Updates made to Observation to replace single slot for value with multiple slots
> Changes to observation

- src/bdchm/schema/bdchm.yaml
Included in this PR are new subclasses to handle measurement records incuding MeasurementObservationSet and MeasurementObservation
> Addition of two measurement classes (MeasurementObservation and MeasurementObservationSet)

- src/bdchm/schema/bdchm.yaml
After discussion with Leena Dave I created initial structures for capturing SDOH using Observation and ObservationSet subclasses
> Initial commit for SDOH Observation and ObservationSet

- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/atherosclerosis.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/atherosclerosis_events_incident.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/atherosclerosis_events_prior.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/baseline_common_covariates.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/blood_cell_count.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/blood_pressure.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/demographic.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/inflammation.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/lipids.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/sleep.md
- resources/human-readable-harmonized-variable-documentation/generated-doc-pages/vte.md
- resources/human-readable-harmonized-variable-documentation/harmonization_documentation_generator.py
in the priority variable worksheet.
Also clarified 'Study (harmonization_units)'. Harmonization units is what the raw topmed doc files call them, but they are the studies for which a given variable has been harmonized.
> Added stuff so I could put links to topmed docs

- src/docs/new_erd.md
Using this command:
`gen-erdiagram src/bdchm/schema/bdchm.yaml -c Entity -c Person -c Demography -c Participant -c ResearchStudy -c Consent -c Visit -c Organization -c TimePoint -c TimePeriod -c ResearchStudyCollection -c Questionnaire -c QuestionnaireItem -c QuestionnaireResponse -c QuestionnaireResponseItem -c QuestionnaireResponseValue -c QuestionnaireResponseValueDecimal -c QuestionnaireResponseValueBoolean -c QuestionnaireResponseValueInteger -c QuestionnaireResponseValueTimePoint -c QuestionnaireResponseValueString -c Condition -c Procedure -c Exposure -c DrugExposure -c DeviceExposure -c DimensionalObservation -c DimensionalObservationSet -c File -c Document -c Specimen -c SpecimenContainer -c SpecimenCreationActivity -c SpecimenQualityObservation -c SpecimenQuantityObservation -c …
> Trying to generate updated ERD

- src/bdchm/schema/bdchm.yaml
This PR addresses [issue #60](https://github.com/RTIInternational/NHLBI-BDC-DMC-HM/issues/60)
> Added attribute value_integer to class Quantity

- src/bdchm/schema/bdchm.yaml
This PR creates a severity attribute for the Condition class
> Initial commit of Condition Severity

- src/bdchm/schema/bdchm.yaml
This PR is related to [issue #70](https://github.com/RTIInternational/NHLBI-BDC-DMC-HM/issues/70)
> Adding permissible value 'HISTORICAL' to ConditionStatusEnum

- src/bdchm/schema/bdchm.yaml
This is addressing [issue #71](https://github.com/RTIInternational/NHLBI-BDC-DMC-HM/issues/71)
> Addition of FamilyRelationshipEnum and its use in Condition.relationship_to_participant

- src/data/examples/alt_measurement_observation.yaml
- src/data/examples/alt_measurement_observation_qualitative.yaml
- src/data/examples/bp_measurement_observation_set.yaml
- src/data/examples/family_medical_history.yaml
- src/data/examples/measurement_observation.yaml
- src/data/examples/patient_condition.yaml
- src/data/examples/patient_medical_history.yaml
This PR adds example data covering Condition, MeasurementObservation, and MeasurementObservationSet classes.
> including some example data

- src/data/examples/drug_exposure.yaml
- src/data/examples/person_participant_demography.yaml
- src/data/examples/sdoh_observation.yaml
> including additional examples per Issue #83

- src/bdchm/schema/bdchm.yaml
Adding a value for "More than one race" to tje Race Enum.
> This commit addresses issue 9 in the HV repo.

- src/bdchm/schema/bdchm.yaml
This PR includes a value for CLINICAL_DIAGNOSIS in the ProvenanceEnum
> Commit to address issue 8 in the HV repo.
